### ISSUE TITLE
request for mimic_cxr_sectioned.csv

### ISSUE THREAD

**Issue by YJSYJSYJS** [holajoa/adaptor-thesis#14]
Thank you for your great work!

I'm reproducing your work with your repo.
I downloaded all of the datasets including mimic-cxr-jpg.
However i couldn't find mimic_cxr_sectioned.csv, which is required in preprocess/mimic_cxr.py.
It seems like the csv file is a combined version of text files from mimic-cxr-jpg 2.0.0.
Can you share your csv file or the way you made it?

**Comment by ming-jq** [comment]
Thanks for your message!
mimic_cxr_sectioned.csv is the officially recommended train/validation/test splits of the MIMIC-CXR-JPG dataset, and is included in the data files. Please find further information and download instructions [here](https://physionet.org/content/mimic-cxr-jpg/2.0.0/).

**Comment by YJSYJSYJS** [comment]
Thanks for your reply!

I read the instruction about mimic-cxr data at the website you linked.
I think mimic-cxr-2.0.0-split.csv is just what you described.

mimic_cxr_sectioned.csv is read by pandas dataframe with the name of text_df in mimic cxr.py. 
So I thought that it might be the combination of text raw data composed of findings and impressions mainly

**Comment by YJSYJSYJS** [comment]
Oh! I found how to generate sectioned.csv in [mimic-cxr github repo](https://github.com/MIT-LCP/mimic-cxr/blob/31901464793d0bb23835092f05bd1aba6af7baff/notebooks/generate-stats-from-paper.ipynb#L1217)
